name: CMake Build Matrix

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Prepare Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@v1.2.0
      with:
        vulkan-query-version: 1.3.250.1
        vulkan-components: Vulkan-Headers, Vulkan-Loader
        vulkan-use-cache: true
    - uses: actions/checkout@v3
    - name: CMake Action
      uses: threeal/cmake-action@v1.3.0
