name: CMake Build Matrix

on: [push]

jobs:
  build-windows-exe:
    name: Build windows executable
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1.4.1
    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@v1.1.1
      with:
        version: 1.3.250.1
        cache: true
    - name: Chocolatey install clang and make
      uses: crazy-max/ghaction-chocolatey@v3
      with:
        args: install llvm make
    - name: Cache Build
      id: restore-cache-build
      uses: actions/cache/restore@v4
      with:
        path: build
        key: ${{ runner.os }}-build
    - name: CMake Action
      uses: threeal/cmake-action@v1.3.0
      with:
        run-build: true
        generator: "Unix Makefiles"
        args: -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_ASM_COMPILER=clang
    - uses: actions/cache/save@v3
      name: Save build cache
      with:
        path: build
        key: ${{ runner.os }}-build
    - name: upload executable
      uses: actions/upload-artifact@v4
      with:
        name: windows
        path: build/main
          #build-linux-elf:
          #  name: Build linux elf executable
          #  runs-on: ubuntu-24.04
          #  steps:
          #  - uses: actions/checkout@v3
          #  - name: Install Vulkan SDK
          #    uses: humbletim/install-vulkan-sdk@v1.1.1
          #    with:
          #      version: 1.3.250.1
          #      cache: true
          #  - name: Install dependencies
          #    uses: awalsh128/cache-apt-pkgs-action@latest
          #    with:
          #      packages: xorg openbox libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libgl-dev libc++-18-dev clang-18 nasm
          #  - name: Cache Build
          #    id: restore-cache-build
          #    uses: actions/cache/restore@v4
          #    with:
          #      path: build
          #      key: ${{ runner.os }}-build
          #  - name: CMake Action
          #    uses: threeal/cmake-action@v1.3.0
          #    with:
          #      args: -DGLFW_BUILD_WAYLAND=0 -DCMAKE_CXX_FLAGS="-fexperimental-library" -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang
          #      run-build: true
          #      c-compiler: clang-18
          #      cxx-compiler: clang++-18
          #  - uses: actions/cache/save@v3
          #    name: Save build cache
          #    with:
          #      path: build
          #      key: ${{ runner.os }}-build
