name: CMake Build Matrix

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@v1.1.1
      with:
        version: 1.3.250.1
        cache: true
    - uses: actions/checkout@v3
    - name: CMake Action
      uses: threeal/cmake-action@v1.3.0
