name: CMake Build Matrix

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@v1.1.1
      with:
        version: 1.3.250.1
        cache: true
    - name: Install wayland
      run: sudo apt-get update && sudo apt-get install --no-install-recommends -y xorg openbox libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libgl-dev libc++-18-dev clang-18
    - name: CMake Action
      uses: threeal/cmake-action@v1.3.0
      with:
        args: -DGLFW_BUILD_WAYLAND=0 -DCMAKE_CXX_FLAGS="-fexperimental-library"
        run-build: true
