name: CMake Build Matrix

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: CMake Action
      uses: threeal/cmake-action@v1.3.0
